### ISSUE TITLE
Camera focus / GCam front camera not working

### ISSUE THREAD

**Issue by ghost** [SyberiaProject-Devices/platform_device_oneplus_oneplus6#6]
After using camera with stock OnePlus app, when you try to use camera from another app like WhatsApp autofocus doesn't work (try to scan a WhatsApp Web QR code, it looks like to be pointed at infinity). Also when you try to use front camera with GCam the app crash.

**Comment by DennySPB** [comment]
Delete or freeze CameraPackage.apk. Then 3d-party cameras will work, but some modes of stock camera will be broken. It cannot posible make it work both for now.
